name: NikGer-exam
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Display SoftUni Username
      run: echo My SoftUni Username is NikGer
    - run: npm install 
    - run: npm install 
    - run: npx playwright install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:unit   
    - run: npm start & while ! nc -z localhost 8080; do sleep 3; done
    - run: npm run test:ui

  deploy:
  
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        serviceId: ${{ secrets.SERVICE_ID }}
        apiKey: ${{ secrets.RENDER_TOKEN }}

